export const ACTIONS = {
    ASTRONAUT: {
        SETUP: 'ASTRONAUT_SETUP',
        INC_X_SPEED: 'ASTRONAUT_INC_X_SPEED',
        INC_Y_SPEED: 'ASTRONAUT_INC_Y_SPEED',
        DEC_X_SPEED: 'ASTRONAUT_DEC_X_SPEED',
        DEC_Y_SPEED: 'ASTRONAUT_DEC_Y_SPEED',
        MOVE_X: 'ASTRONAUT_MOVE_X',
        MOVE_Y: 'ASTRONAUT_MOVE_Y',
        FIRE: 'ASTRONAUT_FIRE',
        COLLISION_ENEMY: 'ASTRONAUT_COLLISION_ENEMY',
        COLLISION_FUEL: 'ASTRONAUT_COLLISION_FUEL',
        COLLISION_OBSTACLE: 'ASTRONAUT_COLLISION_OBSTACLE',
        COLLISION_BONUS: 'ASTRONAUT_COLLISION_BONUS',
        DROP_FUEL: 'ASTRONAUT_DROP_FUEL',
        DIE: 'ASTRONAUT_DIE',
        ADD_SCORE: 'ADD_SCORE',
        SPAWN: 'ASTRONAUT_SPAWN',
        SPAWN_COMPLETE: 'ASTRONAUT_SPAWN_COMPLETE',
        FLY_SPACESHIP: 'ASTRONAUT_FLY_SPACESHIP',
        RESTART: 'ASTRONAUT_RESTART',
        THROTTLE: 'ASTRONAUT_THROTTLE'
    },

    BONUS: {
        SETUP: 'BONUS_SETUP',
        SPAWN: 'BONUS_SPAWN',
        REMOVE: 'BONUS_REMOVE',
        COLLISION_ASTRONAUT: 'BONUS_COLLISION_ASTRONAUT'
    },

    SPACESHIP: {
        ADD_FUEL: 'SPACESHIP_ADD_FUEL',
        FLY: 'SPACESHIP_FLY',
        SETUP: 'SPACESHIP_SETUP',
        MOVE_Y: 'SPACESHIP_MOVE_Y',
        RESTART: 'SPACESHIP_RESTART'
    },

    ENEMY: {
        SETUP: 'ENEMY_SETUP',
        SPAWN: 'ENEMY_SPAWN',
        SPAWN_COMPLETE: 'ENEMY_SPAWN_COMPLETE',
        MOVE_X: 'ENEMY_MOVE_X',
        MOVE_Y: 'ENEMY_MOVE_Y',
        COLLISION_FIRE: 'ENEMY_COLLISION_FIRE',
        COLLISION_OBSTACLE: 'ENEMY_COLLISION_OBSTACLE',
        DIE: 'ENEMY_DIE',
        ADJUST_SPEED: 'ENEMY_ADJUST_SPEED'
    },

    FIRE: {
        FIRE: 'FIRE_FIRE',
        MOVE_X: 'FIRE_MOVE_X',
        MOVE_Y: 'FIRE_MOVE_Y',
        COLLISION_ENEMY: 'FIRE_COLLISION_ENEMY',
        COLLISION_OBSTACLE: 'FIRE_COLLISION_OBSTACLE'
    },

    OBSTACLE: {
        COLLISION_FIRE: 'OBSTACLE_COLLISION_FIRE'
    },

    STAGE: {
        GENERATE: 'STAGE_GENERATE',
        START: 'STAGE_START',
        GAME_OVER: 'STAGE_GAME_OVER',
        PAUSE: 'STAGE_PAUSE',
        NEXT_LEVEL: 'STAGE_NEXT_LEVEL',
        SPAWN_GEM: 'STAGE_SPAWN_GEM',
        COLLECT_GEM: 'STATE_COLLECT_GEM'
    }
};